server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:FlightAvailability
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
#    show-sql: true
